-- Camp master table for admin-managed camp options used in student form dropdown.
-- Run this in Supabase SQL editor.

create table if not exists public.camp_master (
  id bigint generated by default as identity primary key,
  camp_name text not null,
  camp_date date not null,
  created_by text,
  created_at timestamptz not null default now(),
  unique (camp_name, camp_date)
);

create index if not exists idx_camp_master_name on public.camp_master (camp_name);
create index if not exists idx_camp_master_date on public.camp_master (camp_date desc);

-- Enable RLS
alter table public.camp_master enable row level security;

-- RLS policies
create policy "Allow anon users to select camps" on public.camp_master
  for select using (true);

create policy "Allow authenticated users to select camps" on public.camp_master
  for select using (true);

create policy "Allow authenticated users to insert camps" on public.camp_master
  for insert with check (true);

-- Grant permissions
grant select on public.camp_master to anon;
grant select, insert on public.camp_master to authenticated;
grant usage, select on sequence public.camp_master_id_seq to authenticated;
